"""added motor columns

Revision ID: 189dc2eb7b60
Revises: 72486a91cce7
Create Date: 2024-03-08 16:35:44.107782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189dc2eb7b60'
down_revision = '72486a91cce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
